services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin123  # 必须设置密码

    # volumes:
    #   - /home/printer/pgdata:/var/lib/postgresql/data  # 关键数据持久化配置[1](@ref)[5](@ref)

  web:
    build: .
    command: gunicorn -c gunicorn.py keymanager.wsgi:application
    volumes:
      - .:/code
      - ./staticfiles:/code/staticfiles
    depends_on:
      - db


  nginx:
    image: nginx:latest
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - web