services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin123  # 必须设置密码

    volumes:
      - /home/deploy/pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn -c gunicorn.py keymanager.wsgi:application
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    depends_on:
      - db


  nginx:
    image: nginx:latest
    volumes:
      - ./auto-updates:/app/auto-updates
      - ./smallest-updates:/app/smallest-updates
      - ./staticfiles:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - web