# Generated by Django 5.2 on 2025-04-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='机器码')),
                ('type', models.IntegerField(choices=[(1, '3D彩'), (2, '六合彩')], default=1, verbose_name='证书类型')),
                ('remark', models.TextField(verbose_name='备注')),
                ('enabled', models.IntegerField(choices=[(1, '启用'), (0, '停用')], default=1, verbose_name='是否启用')),
                ('status', models.IntegerField(choices=[(1, '在线'), (0, '离线')], default=1, verbose_name='机器状态')),
                ('expire_time', models.IntegerField(default=365, verbose_name='可用时间天数')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
