# Generated by Django 5.2 on 2025-04-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licence',
            name='expire_time',
        ),
        migrations.AlterField(
            model_name='licence',
            name='type',
            field=models.IntegerField(choices=[(1, '3D彩'), (2, '六合彩')], default=1, verbose_name='客户端类型'),
        ),
    ]
