# Generated by Django 5.2 on 2025-04-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0003_remove_licence_expire_time_alter_licence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='enabled',
            field=models.IntegerField(choices=[(1, '启用'), (0, '停用')], default=0, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='status',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], default=0, verbose_name='机器状态'),
        ),
        migrations.AddConstraint(
            model_name='licence',
            constraint=models.UniqueConstraint(fields=('machine_code', 'type'), name='unique_machine_type'),
        ),
    ]
