# Generated by Django 5.2 on 2025-04-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0004_alter_licence_enabled_alter_licence_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licence',
            options={'verbose_name': '打印机', 'verbose_name_plural': '打印机'},
        ),
        migrations.RemoveConstraint(
            model_name='licence',
            name='unique_machine_type',
        ),
    ]
