# Generated by Django 5.2 on 2025-04-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0005_alter_licence_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='enabled',
            field=models.IntegerField(choices=[(1, '启用'), (0, '停用')], default=1, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='machine_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='机器码'),
        ),
    ]