# Generated by Django 5.2 on 2025-04-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_code', models.CharField(max_length=100, verbose_name='票面字符串码')),
                ('serial_number', models.IntegerField(verbose_name='序列号')),
                ('orders_data', models.JSONField(verbose_name='订单详情')),
                ('ver_ticket_code', models.CharField(max_length=100, verbose_name='验证票码')),
                ('play_method', models.CharField(max_length=50, verbose_name='玩法')),
                ('draw_time', models.DateField(blank=True, null=True, verbose_name='开奖日期')),
                ('last_period_data', models.CharField(blank=True, max_length=255, null=True, verbose_name='上期数据')),
                ('store_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='门店地址')),
                ('machine_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='机器码')),
                ('sale_period', models.CharField(blank=True, max_length=20, null=True, verbose_name='销售期号')),
                ('copywriting', models.TextField(blank=True, null=True, verbose_name='文案')),
                ('activity', models.BooleanField(default=False, verbose_name='活动')),
                ('sale_time', models.DateTimeField(blank=True, null=True, verbose_name='销售时间')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('machine_id', models.CharField(max_length=255, unique=True, verbose_name='机器ID')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
