# Generated by Django 5.2 on 2025-04-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='draw_time',
            new_name='drawTime',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_period_data',
            new_name='lastPeriodData',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='machine_code',
            new_name='machineCode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='machine_id',
            new_name='machineId',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orders_data',
            new_name='orders',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='play_method',
            new_name='playMethod',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='sale_period',
            new_name='salePeriod',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='sale_time',
            new_name='saleTime',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='serial_number',
            new_name='serialNumber',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='store_address',
            new_name='storeAddress',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='str_code',
            new_name='strCode',
        ),
    ]
