# Generated by Django 5.2 on 2025-04-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_draw_time_order_drawtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ver_ticket_code',
            new_name='verTicketCode',
        ),
    ]
