# Generated by Django 5.2 on 2025-04-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_ver_ticket_code_order_verticketcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='drawTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='开奖日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='saleTime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='销售时间'),
        ),
    ]
