# Generated by Django 5.2 on 2025-04-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_drawtime_alter_order_saletime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='machineId',
            field=models.CharField(max_length=255, verbose_name='机器ID'),
        ),
    ]
